server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: riton
  datasource:
    driver-class-name: ${riton.datasource.driver-class-name}
    url: ${riton.datasource.url}
    username: ${riton.datasource.username}
    password: ${riton.datasource.password}
  redis:
    host: ${riton.redis.host}
    port: ${riton.redis.port}
    password: ${riton.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.riton.entity # 别名扫描包
logging:
  level:
    com.riton: debug
rocketmq:
  name-server: ${riton.rocketmq.address}
  producer:
    group: ${riton.rocketmq.group}
